name: Validate

on:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3.5.0"
      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          ignore: "brands"
          category: "integration"
          comment: false

